### PR TITLE
Link fixes design updates

### LINKED ISSUE #156: fix: profile page button does not work :(

### PR DESCRIPTION
**Pull request by mozsarmate**

### CODE REVIEW

**Comment by mozsarmate** [comment]
haloooo

File: packages/client/src/components/collection/CollectionListItem.tsx [hunk 1]
```diff
@@ -23,7 +23,14 @@ export function CollectionListItem({ collection }: Props) {
...
           fill={true}
           className={cn('mt-3 overflow-hidden rounded-xl object-cover brightness-50', hasImageError ? 'bg-black' : 'bg-white')}
-          onError={() => setHasImageError(true)}
+          onError={() => {
+            setHasImageError(true)
+            console.log('error')
+          }}
+          onInvalid={() => {
+            setHasImageError(true)
+            console.log('error')
```
Comment (FearsomeRover) [inline packages/client/src/components/collection/CollectionListItem.tsx:32]: Maybe we can leave this out of prod...

**Review by FearsomeRover — APPROVED** [review]
